apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tier-status-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tier-status-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
